"""Add application details

Revision ID: 7e037e51910a
Revises: bf604e792f64
Create Date: 2025-07-28 01:10:24.065947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e037e51910a'
down_revision: Union[str, None] = 'bf604e792f64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_applications', sa.Column('experience', sa.Text(), nullable=True))
    op.add_column('job_applications', sa.Column('cover_letter', sa.Text(), nullable=True))
    op.add_column('job_applications', sa.Column('resume_url', sa.String(), nullable=True))
    op.add_column('job_applications', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_applications', 'status')
    op.drop_column('job_applications', 'resume_url')
    op.drop_column('job_applications', 'cover_letter')
    op.drop_column('job_applications', 'experience')
    # ### end Alembic commands ###
