"""Add application fields

Revision ID: fe8960cb01fd
Revises: 7e037e51910a
Create Date: 2025-07-28 01:38:14.173330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe8960cb01fd'
down_revision: Union[str, None] = '7e037e51910a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_applications', sa.Column('resume_link', sa.String(), nullable=False))
    op.alter_column('job_applications', 'experience',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('job_applications', 'cover_letter',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('job_applications', 'resume_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_applications', sa.Column('resume_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('job_applications', 'cover_letter',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('job_applications', 'experience',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('job_applications', 'resume_link')
    # ### end Alembic commands ###
